### PR TITLE
update front page

### PR DESCRIPTION
**Pull request by sashakames**
Remove "old news" - add the R&D100 logo
This hasn't been previewed in Jekyll but hopefully we can try it out if not too much trouble

### CODE REVIEW

**Comment by mauzey1** [comment]
The logo appears really tiny on the left of bullet point list.
Screenshot-2019-7-1 ESGF Home Page
Should it be on the side, or should it be on top of the first paragraph?

**Comment by sashakames** [comment]
@mauzey1  This should show the correct size and acceptable placement, so on the side.  If we can align the top of the image with the text even better.
Screen Shot 2019-07-02 at 9 20 01 AM

**Comment by mauzey1** [comment]
Screenshot-2019-7-2 ESGF Home Page

I added new CSS for these changes.
```
    img.rd100 {
        max-height: 180px;
        max-width: 180px;
    }

    td.rd100 {
        vertical-align: top;
    }

...

<td class="rd100">
    <img class="rd100" src="images/RND100.png">
</td>
```

**Comment by sashakames** [comment]
@mauzey1 now that I merged your update, hopefully the original PR will look right and we can merge, thanks!

**Pull request merged**
